stages:
  - test

test:
  stage: test
  image: python:3.8-buster
  script:
  - apt-get update -qy
  - apt-get install -y pipenv
  - pipenv install --dev
  - PYTHONPATH=${PYTHONPATH}:${PWD} pipenv run pytest
