version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ETL-Assembly-Development"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentName=\"development\""
tags = "application=\"etl-assembly\""
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o8t9iqzubhru"
s3_prefix = "ETL-Assembly-Development"
