version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ETL-Assembly-Development"
s3_bucket = "sourcebucket-trustar-etl-assembly"
s3_prefix = "development"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentName=\"Development\""
tags = "application=\"etl-assembly\"
