AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ETL-Assembly

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    CodeUri: .
    Runtime: python3.8

Parameters:
  EnvironmentName:
    Description: The environment to deploy this to.
    Type: String
    Default: Staging
    AllowedValues:
      - Staging
      - Production
    ConstraintDescription: "Must be one of: Staging, Production"

Resources:
  JobCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: serverless_assembly.job_creation.lambda_handler


  CronSchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: serverless_assembly.cron_scheduler.lambda_handler
    Events:
      JobTableUpsert:
        Type: DynamoDB
        Properties:
          StartingPosition: LATEST
          Stream: !GetAtt JobTable.StreamArn
          Enabled: True


  ExtractJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
      ContentBasedDeduplication: True
      FifoQueue: True
      QueueName: !Sub ${EnvironmentName}-etl-assembly-extract-jobs.fifo
      VisibilityTimeout: 900

  TransformJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: True
      FifoQueue: True
      QueueName: !Sub ${EnvironmentName}-etl-assembly-transform-jobs.fifo
      VisibilityTimeout: 900

  LoadJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: True
      FifoQueue: True
      QueueName: !Sub ${EnvironmentName}-etl-assembly-load-jobs.fifo
      VisibilityTimeout: 900

  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-etl-assembly-templates

  UserConfTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-etl-assembly-user-configs

  JobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-etl-assembly-jobs
