AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ETL-Assembly

Parameters:
  EnvironmentName:
    Description: The environment to deploy this to.
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
      - development
    ConstraintDescription: "Must be one of: staging, production, development"

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: python3.8
    Environment:
      Variables:
        JOB_TABLE: !Sub ${EnvironmentName}-JobTable
        USER_CONF_TABLE: !Sub ${EnvironmentName}-UserConfTable
        TEMPLATES_TABLE: !Sub ${EnvironmentName}-TemplatesTable
        EXTRACT_JOBS_QUEUE: !Ref ExtractJobsQueue
        TRANSFORM_JOBS_QUEUE: !Ref TransformJobsQueue
        LOAD_JOBS_QUEUE: !Ref LoadJobsQueue
        HISTORY_JOBS_QUEUE: !Ref HistoryJobQueue
        HISTORY_MESSAGES_RATE: 3
        BIG_PAYLOADS_BUCKET: !Sub ${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket
        LOGLEVEL: DEBUG

Resources:
  EtlAssemblyCoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${EnvironmentName}-EtlAssemblyCoreLayer
      Description: This is the core functionality and deps for ETL Assembly
      ContentUri: .
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile

  JobCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: job_creation.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-JobCreationFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt JobTable.Arn
                - !GetAtt TemplatesTable.Arn
                - !GetAtt UserConfTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt ExtractJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
    Metadata:
      BuildMethod: makefile

  ExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: extraction.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-ExtractionFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt JobTable.Arn
                - !GetAtt TemplatesTable.Arn
                - !GetAtt UserConfTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt JobTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt TransformJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
              Resource:
                - !GetAtt ExtractJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
      Events:
        ExtractionJobEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ExtractJobsQueue.Arn
            BatchSize: 1
    Metadata:
      BuildMethod: makefile

  HistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: historical_extraction.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-HistoryFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt JobTable.Arn
                - !GetAtt TemplatesTable.Arn
                - !GetAtt UserConfTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt JobTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt TransformJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:ReceiveMessage
              Resource:
                - !GetAtt HistoryJobQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
      Events:
        Scheduling:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

    Metadata:
      BuildMethod: makefile

  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: transform.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-TransformFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt JobTable.Arn
                - !GetAtt TemplatesTable.Arn
                - !GetAtt UserConfTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt LoadJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
              Resource:
                - !GetAtt TransformJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
      Events:
        ExtractionJobEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TransformJobsQueue.Arn
            BatchSize: 10
    Metadata:
      BuildMethod: makefile

  LoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: load.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-LoadFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt JobTable.Arn
                - !GetAtt TemplatesTable.Arn
                - !GetAtt UserConfTable.Arn

        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
              Resource:
                - !GetAtt LoadJobsQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
      Events:
        ExtractionJobEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt LoadJobsQueue.Arn
            BatchSize: 1
    Metadata:
      BuildMethod: makefile

  CronSchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cron_scheduler.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-CronSchedulerFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Events:
        JobTableUpsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: !GetAtt JobTable.StreamArn
            Enabled: True
      Environment:
        Variables:
          JOB_CREATION_FUNCTION: !Sub ${EnvironmentName}-JobCreationFunction
          JOB_CREATION_FUNCTION_ARN: !GetAtt JobCreationFunction.Arn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - events:PutRule
                - events:PutTargets
                - events:RemoveTargets
                - events:DeleteRule
              Resource: "arn:aws:events:*:*:rule/etl_assembly_job_*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt JobTable.Arn
                - !GetAtt TemplatesTable.Arn
                - !GetAtt UserConfTable.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - lambda:AddPermission
                - lambda:RemovePermission
              Resource:
                - !GetAtt JobCreationFunction.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt HistoryJobQueue.Arn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket/*"
    Metadata:
      BuildMethod: makefile

  ExtractJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
      QueueName: !Sub ${EnvironmentName}-ExtractJobsQueue
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterExtractJobsQueue.Arn
        maxReceiveCount: 5

  DeadLetterExtractJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-DeadLetterExtractJobsQueue
      VisibilityTimeout: 900

  TransformJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-TransformJobsQueue
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterTransformJobsQueue.Arn
        maxReceiveCount: 5

  DeadLetterTransformJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-DeadLetterTransformJobsQueue
      VisibilityTimeout: 900

  LoadJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-LoadJobsQueue
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterLoadJobsQueue.Arn
        maxReceiveCount: 5

  DeadLetterLoadJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-DeadLetterLoadJobsQueue
      VisibilityTimeout: 900

  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-TemplatesTable

  UserConfTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-UserConfTable

  JobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-JobTable

  BigPayloadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-trustar-etl-assembly-bigpayloadsbucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  HistoryJobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub ${EnvironmentName}-HistoryJobQueue
        VisibilityTimeout: 900
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DLHistoryJobQueue.Arn
          maxReceiveCount: 3

  DLHistoryJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-DLHistoryJobQueue
      VisibilityTimeout: 900
