AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ETL-Assembly

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: python3.8
    Environment:
      Variables:
        JOB_CREATION_FUNCTION: !Sub ${EnvironmentName}-JobCreationFunction
        JOB_TABLE: !Sub ${EnvironmentName}-JobTable
        USER_CONF_TABLE: !Sub ${EnvironmentName}-UserConfTable
        TEMPLATES_TABLE: !Sub ${EnvironmentName}-TemplatesTable


Parameters:
  EnvironmentName:
    Description: The environment to deploy this to.
    Type: String
    Default: Staging
    AllowedValues:
      - Staging
      - Production
    ConstraintDescription: "Must be one of: Staging, Production"

Resources:
  EtlAssemblyCoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${EnvironmentName}-EtlAssemblyCoreLayer
      Description: This is the core functionality and deps for ETL Assembly
      ContentUri: .
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile

  JobCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: job_creation.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-JobCreationFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
    Metadata:
      BuildMethod: makefile

  CronSchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cron_scheduler.lambda_handler
      FunctionName: !Sub ${EnvironmentName}-CronSchedulerFunction
      Layers:
        - Ref: EtlAssemblyCoreLayer
      Events:
        JobTableUpsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: !GetAtt JobTable.StreamArn
            Enabled: True

    Metadata:
      BuildMethod: makefile

  ExtractJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
      ContentBasedDeduplication: True
      FifoQueue: True
      QueueName: !Sub ${EnvironmentName}-ExtractJobsQueue.fifo
      VisibilityTimeout: 900

  TransformJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: True
      FifoQueue: True
      QueueName: !Sub ${EnvironmentName}-TransformJobsQueue.fifo
      VisibilityTimeout: 900

  LoadJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: True
      FifoQueue: True
      QueueName: !Sub ${EnvironmentName}-LoadJobsQueue.fifo
      VisibilityTimeout: 900

  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-TemplatesTable

  UserConfTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-UserConfTable

  JobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${EnvironmentName}-JobTable
